### ISSUE TITLE
Upgrade issue seen in DCS

### ISSUE THREAD

**Issue by lv426hudson** [mbucchia/Pimax-OpenXR#10]
I have been using pimax oxr 0.1.2 with oxrtk 1.1.0 in DCS and it was smooth as butter. I upgraded to 0.1.7 and oxrtk 1.1.4 and was getting a weird stutter at approx 1s intervals. Restarted a few times same issue. Downgraded back to 0.1.2 and oxrtk 1.1.0 and its smooth again, weird.

**Comment by lv426hudson** [comment]
Is it worth trying the newer 0.1.7 with the older 1.1.0 oxrtk to narrow down what could be causing this? Or would this be incompatible. Cheers.

**Comment by mbucchia** [comment]
Thanks. Can you try to isolate which component?

Like try PimaxXR alone, no OpenXR Toolkit. Is going from 0.1.2 to 0.1.7 causing the issue?

If not, then re add OpenXR Toolkit and do the same process. Is going from 1.1.0 to 1.1.4 causing the issue?

**Comment by lv426hudson** [comment]
Thanks mate. I will give all this a try, will probably be tomorrow now, the Mrs will kill me if i go back on DCS :D

**Comment by lv426hudson** [comment]
Hi, so I've just tested every version of Pimax-OpenXR available to download here, the issue appears to lie with the Pimax-OpenXR runtime and not with the oxrtk. So all these tests i did with oxrtk uninstalled. The issues appear to start at 0.1.4.

I am using the 64bit openvr_api.dll downloaded from here:
https://znix.xyz/OpenComposite/download.php?arch=x64&branch=openxr

- SteamVR baseline, DCS runs fine through SteamVR
- Pimax-OpenXR 0.1.0, runs amazing
- Pimax-OpenXR 0.1.2 runs amazing
- Pimax-OpenXR 0.1.4 Headset tracking goes absolutely crazy, spinning around all over the place
- Pimax-OpenXR 0.1.6 has a weird interval stutter, seems to happen regardless of graphic load (in DCS menu area)
- Pimax-OpenXR 0.1.7 exactly same as 0.1.6

Cheers,

**Comment by mbucchia** [comment]
Thanks for digging. Nobody else has reported this issue with DCS so I'm not sure what's going on.

Can you tell me what version of the Pimax software you are using?

I am adding some more statistics in the next version so hopefully this will help us track it down.

**Comment by mbucchia** [comment]
Oh and to be sure, you are using the newer OpenComposite and not the old OpenComposite-ACC?

**Comment by lv426hudson** [comment]
Hi, My Pimax software versions are as follows
- PiTool 1.0.1.277
- Headset firmware 2.1.255.299

Just for more information, I am running at render quality 1.0, normal FOV, smart smoothing off and compulsive smoothing at 1/2 @ 90hz.

With regards to OpenComposite, I am using the per game install method from the link above, is this correct? Is it worth trying again with the system wide installer from the link below?

https://gitlab.com/znixian/OpenOVR/-/tree/openxr

Cheers,

**Comment by lv426hudson** [comment]
> I am aware of some issues with lighthouse tracking that could be related. Have you tried with 9-axis only by any chance?
> 

No mate i havent ive always just used 2 x lighthouse 2.0. But i will try 9 axis today at some point and report back. Cheers.

**Comment by lv426hudson** [comment]
> I am aware of some issues with lighthouse tracking that could be related. Have you tried with 9-axis only by any chance?
> 

Update: i tested 0.1.7 with 9 axis and i would say it is an improvement but the hitches are still there if only minor. I also tried 0.1.2 on 9 axis and this was smooth as butter. The hitches/stutters i see on 0.1.7 are more apparent when moving head left to right laterally. Just my luck that. It doesnt work well for me ;-(

**Comment by mbucchia** [comment]
Between 0.1.2 and 0.1.4, I upgraded to the newer Pimax SDK and apparently there are some fallout from this. Need to understand what's happening with it. I am investigating a few leads, I might need you to capture some more data for me eventually. Thanks.

**Comment by lv426hudson** [comment]
> Between 0.1.2 and 0.1.4, I upgraded to the newer Pimax SDK and apparently there are some fallout from this. Need to understand what's happening with it. I am investigating a few leads, I might need you to capture some more data for me eventually. Thanks.

Yep that's no problem mate. When I tested moving from 0.1.2 to 0.1.4, that's when the head tracking went absolutely vomit inducing. like the headset was spinning in circles wildly. For now I am just using 0.1.2 as this is wonderful. Cheers.

**Comment by mbucchia** [comment]
I am hopeful that the issue will be fixed by e304048e548500be6ce5ed937d7d8acab2124b1d.

Leaving this open until release 0.2.0 (not ready yet) and you can confirm the fix.

**Comment by mbucchia** [comment]
Can you try new version 0.2.0 and see if that resolved the problem?

**Comment by lv426hudson** [comment]
Hi mate, i have just tried installed 0.2.0, but sadly I am still getting the weird frequent stutter/micro glitches. Uninstalled and reinstalled 0.1.2 and its perfect again :-( I'm not sure if its visible on the DCS mirror, but I will try and capture it to show you. This might not be for a few days as I will be moving my custom loop into another case throughout the week.

**Comment by mbucchia** [comment]
Can you try this build and see if it helps?

[PimaxXR-0.2.3c.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9124781/PimaxXR-0.2.3c.zip)

Thanks!

**Comment by lv426hudson** [comment]
Hi, yes i will give this a try today. Also i tried 0.2.2 last night and this also has the same issue for me. I did notice that if i disable compulsive smooth in pi tool that the issue more or less disappears, if this is a clue.

**Comment by lv426hudson** [comment]
> Can you try this build and see if it helps?
> 
> [PimaxXR-0.2.3c.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9124781/PimaxXR-0.2.3c.zip)
> 
> Thanks!

I have great news, this build appears to have resolved my issue with the ghost stuttering frames. Using PimaxXR 0.2.3c in conjunction with OXRTK 1.1.4 I now have the same performance as if using POXR 0.1.2 and OXRTK 1.1.0. This was only a quick test, but the issue would have been apparent right away. I will be having a longer play session later today and update if any issues arise. But thank you for your efforts in this :-) Much appreciated.

**Comment by lv426hudson** [comment]
On a side note, just an observation in 0.1.2 when entering DCS i would have to centre my VR twice to get it correct, the first press centres somewhere way off in front and to the left, and the second press centres it correctly. I also see this behaviour in 0.2.3c. Non of the builds between needed 2 presses.

**Comment by mbucchia** [comment]
How do you re-center in DCS?

**Comment by lv426hudson** [comment]
DCS has its own "centre vr headset" bind you can set. 

OK so i have been flying for a couple hours now rotating between 0.1.2 and 0.2.3c, and i must say i still think (for me) 0.1.2 performs better. Although 0.2.3c is a massive improvement i still get the occasional frame glitch that i just don't see in 0.1.2 :-/

**Comment by mbucchia** [comment]
The stutter issue is fixed in 9e8b5cf9960164552abc6991a93aa9422f628efa.

Remaining performance issues with Smart Smoothing will be addressed in #12.
