### ISSUE TITLE
Smart smoothing performance Issue

### ISSUE THREAD

**Issue by T0mmyVR** [mbucchia/Pimax-OpenXR#12]
Hi Im using a pimax 8kx and I get around 30% worse performance when using openxr vs steamvr.
With openxr toolkit enabled I get one black line on each side of the display as well.

**Comment by mbucchia** [comment]
This GitHub issue will remain open to track work on the Smart Smoothing incorrectly selecting 1/3 when 1/2 should be used. I'm currently working with Pimax developers to understand the issue.
