### ISSUE TITLE
xrPathToString XR_ERROR_PATH_INVALID errors in the log. Trying to use Index Controllers

### ISSUE THREAD

**Issue by Ivarpoiss** [mbucchia/Pimax-OpenXR#14]
MSFS, Pimax 5KS, and trying to use Index Controllers. Trace crashes the VR app.

**Comment by mbucchia** [comment]
Thanks. I don't have index controllers unfortunately, I'm trying to find a pair to borrow.

**Comment by mbucchia** [comment]
This should be fixed by 85318cae42e920d930de58564a65f291e826c88a. This change will be released in PimaxXR 0.2.1 (hopefully soon).

**Comment by Ivarpoiss** [comment]
Not quite. I tried to test it on my couch but ended up playing with the code. Several issues. 
The physical controller name is "knuckles\0" (pvr? trailing 0 in std::string) 
getActionSide check names shouldn't contain trailing slashes.

If you could quickly brief/point me how to debug/test this type of stuff efficiently, I could try to contribute. Like maybe a dummy host VR app that could be attacked with the debugger or something. I'm not really familar with Windows, MSVS, VR, etc.

**Comment by mbucchia** [comment]
I fixed the trailing 0 issue in another commit that I haven't pushed yet.

**Comment by mbucchia** [comment]
> getActionSide check names shouldn't contain trailing slashes.

For that one, what app? Can please upload a trace log?

**Comment by mbucchia** [comment]
This has the trailing 0 fix: 5dd49931c7c4e98a8db6125f47b9014c81d07a63

I also see what you mean now for the trailing slash. `getActionSide()` was initially meant to only handle full paths, but it's used in `xrGetCurrentInteractionProfile()` which may also pass top-level paths only. Fixed in 527e642b27b03893f35536880eb7a960a60ac891.

**Comment by mbucchia** [comment]
There is one more bug with the controller management system, that makes the values of `changedSinceLastSync` returned incorrectly. This can lead to issues with certain apps. It's not specific to Index controller though.

Lmk if the latest changes work better.

**Comment by Ivarpoiss** [comment]
Thanks, should be good for now!

> For that one, what app? Can please upload a trace log?

Sorry, that was just a generic question, unrelated to this issue. I was just wondering about the workflow on how do you debug this type of project most efficiently (time wise). Maybe a suggestion for a good dummy VR app.

**Comment by mbucchia** [comment]
I normally use the standard "HelloXR" app from the Khronos SDK: https://github.com/KhronosGroup/OpenXR-SDK-Source (under `src/tests/hello_xr`)

I also use StereoKit for something doing more rendering: https://stereokit.net/

Both can be found in a compiled version here: https://mbucchia.github.io/OpenXR-Toolkit/download/TestApps.zip

If I'm doing some testing with OpenComposite (non-OpenXR apps), I use https://github.com/JamesBear/directx11_hellovr

**Comment by mbucchia** [comment]
Is the Index working OK now?

**Comment by mbucchia** [comment]
Someone else reported that their Index controllers work. Closing.
