### ISSUE TITLE
High latency / rubberbanding

### ISSUE THREAD

**Issue by Ivarpoiss** [mbucchia/Pimax-OpenXR#15]
Not sure if this could be just a MSFS or Pimax issue. Happens only in some sessions.

AMD 6900X, MSFS. This effect is constant, even in the menu at 90fps indicated. No cpu bottleneck. I don't know if it's motion tracking or frames. But it stutters and feels like it lags at least 4-6 frames behind. No Pimax motion smoothing or compulsive smooth used. Parallel projection is off. Both with or without OpenXR Toolkit active.

**Comment by mbucchia** [comment]
Version?

**Comment by Ivarpoiss** [comment]
Can't reproduce anymore. Maybe Pimax issue then. It was the latest main commit (at this time) 12741547fb1b835d86fd6b36082247b6cce6c40e

Maybe compulsive smooth settings not synced or something. Because I also switched to using another 5KS right about then.

**Comment by mbucchia** [comment]
Weird. Thanks for following up.
