### ISSUE TITLE
OpenXR Call failed. Aborting. (PimaxXR version 2,0)

### ISSUE THREAD

**Issue by JanssenP** [mbucchia/Pimax-OpenXR#16]
![image](https://user-images.githubusercontent.com/17250381/177210876-c82c91b2-91aa-4de5-afa9-f529ac6a8bde.png)

**Comment by mbucchia** [comment]
You are using the old OpenComposite which is not supported.

https://mbucchia.github.io/OpenXR-Toolkit/opencomposite.html#dont-use-the-legacy-opencomposite-acc-aka-v063

Please upgrade.

**Comment by JanssenP** [comment]
It works. Thnx.

**Comment by mbucchia** [comment]
Yaya! Thanks for following up!
