### ISSUE TITLE
Get this message from 0.1.4 upwards

### ISSUE THREAD

**Issue by JanssenP** [mbucchia/Pimax-OpenXR#17]
![image](https://user-images.githubusercontent.com/17250381/177590597-a49640e2-58de-4afc-bf65-e7ee5f5848bf.png)

**Comment by mbucchia** [comment]
Did you say yesterday that things worked?

**Comment by mbucchia** [comment]
Please follow these instructions when filing issues: attach logs and traces. Nothing I can do without them:

https://github.com/mbucchia/Pimax-OpenXR/wiki#having-issues

**Comment by JanssenP** [comment]
Everything works fine with version 0.1.2

**Comment by JanssenP** [comment]
[PimaxXR.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9056568/PimaxXR.zip)

**Comment by JanssenP** [comment]
Everything works fine with v0.1.2

**Comment by mbucchia** [comment]
Do you have an up-to-date version of Pitool?

Can you try disabling Vulkan in OpenComposite: look for `initUsingVulkan` on https://gitlab.com/znixian/OpenOVR/-/tree/openxr

It's just a matter of creating an `opencomposite.ini` file with the corresponding config option.

**Comment by JanssenP** [comment]
pitool v1.0.1.277
I don't have a clue where to put this .ini file.

**Comment by mbucchia** [comment]
That's why I linked the OpenComposite page. 3 seconds of searching for text in it: https://gitlab.com/znixian/OpenOVR/-/tree/openxr#configuration-file

**Comment by mbucchia** [comment]
No updates from the user in 3 weeks. Closing.
