### ISSUE TITLE
Smart/Motion Smoothing ratio doesn't "recover" as easily as with Steam VR.

### ISSUE THREAD

**Issue by DJSlane** [mbucchia/Pimax-OpenXR#18]
I've noted that the threshold for returning to 1:2 motion smoothing doesn't occur as easily with PimaxXR. This may be due to increased overhead. But for example if I pause a scene at 42 FPS will go to 25 FPS (1:3 MS); then it will return to 1:3 only when my frametimes are well above the 1:2 threshold (somewhere between 50-55FPS); then it releases to 1:2 MS (37.5FPS), whereas with SteamVR I can do that same at 42FPS, and although it first goes to 1:3 for a few seconds (which I would think it shouldn't), it recovers after 1-3 seconds to 1:2. On the other hand, SteamVR will get tripped back to 1:3 every so often as it only takes a single frame-time below the 37.5 fps equivalent to trip back into 1:3 mode for a few seconds. (this is a "bouncing" MS issue I have reported to Pimax, requesting a way to disable 1:3 as was true in their old versions of Pitool before .271)

**Comment by DJSlane** [comment]
Futhermore, the 1:3 motion smoothing appears to get tripped as well to 1:3 at a threshold of ~50, such that it's a difference in thresholds altogether it appears.

**Comment by DJSlane** [comment]
After some more testing It appears that in 90Hz mode the threshold to recover/fall from/to 1:3 to 1:2 is at 60FPS. So there's a bit of trend where MS thresholds are at 2/3 Hz. I initially thought it was MS overhead, but perhaps it's a miscalculation?

This begs a question: Everytime MS is tripped in either SteamVR and PimaxXR. it goes to 1:3 MS first. Can that be avoided?

**Comment by mbucchia** [comment]
I submit frames as fast as the Pimax API and the game allow me to. I have no control over any of the things you've described unfortunately.

I'm going to continue looking into why we're getting 1/3 when we should be getting 1/2, but I'm not super hopeful that this is something I can control.

**Comment by DJSlane** [comment]
Ok Probably is a Pitool error, which I've reported to them. It's so nuanced and complex that I'm sure it won't be taken seriously hahah. But I gotta try. Meanhwile I'm awaiting a 120hz update so that at least if I do get 1:3 it's at 40 fps instead of 25.

**Comment by mbucchia** [comment]
The Smart Smoothing issues will be tracked under #12.
