### ISSUE TITLE
Without SteamVR I have no desktop overlays available, can anyone recommend any?

### ISSUE THREAD

**Issue by JBB888** [mbucchia/Pimax-OpenXR#19]
So I normally use OVR toolkit while gaming in VR to see my tv on second screen, is there any alternative to do this without steamVR running? thanks

**Comment by mbucchia** [comment]
This is expected when you leave the SteamVR ecosystem, and until someone create a similar ecosystem for OpenXR, there is no solution.

**Comment by JBB888** [comment]
ok, thanks mate
