### ISSUE TITLE
Update Pimax SDK

### ISSUE THREAD

**Issue by SEt-t** [mbucchia/Pimax-OpenXR#2]
There is newer version of native SDK: v1.22. It can be found on official site as pvr_windows_sdk_setup.zip (called "Download UnitySDK").

**Comment by mbucchia** [comment]
Thank you! I had no idea and was so confused about where to find that download!!

**Comment by mbucchia** [comment]
Looking at the difference now, there isn't too much new in that 1.22 SDK, at least nothing that will be making a huge difference right away. Main additions are:

- Support controller model rendering 
- support Hand tracking (can already be done via Ultraleap API layer)
- support eye tracking (already done in OpenXR Toolkit)
- support depth reprojection (will definitely include this, but no app besides Unity is using this today)

I'm glad to have a newer version! There is also a sample code that answers a few questions.

**Comment by mbucchia** [comment]
I've made that change earlier and I'm getting some instabilities now with pvr_beginFrame segfaulting out of nowhere. Will investigate.

**Comment by mbucchia** [comment]
This was done in commit 25d701673388ef7c3ca55e2f022a7c0c8c4532aa.
