### ISSUE TITLE
Flickering when parallel projection and smart smoothing are both  enabled

### ISSUE THREAD

**Issue by damien022** [mbucchia/Pimax-OpenXR#22]
First, thank you for this very useful tool and for making my 8KX work with OpenXR.
I need to enable Parallel Projection with DCS, as otherwise I have cross-eyed issues when zooming (and even more with Spyglass zoom).
Even with 0.2.4, when PP is enabled, I get black flickering on the left and right edges of the screen. There is no such flickering with OpenVR.
Any ideas what might be causing it?

**Comment by mbucchia** [comment]
Can you try to disable the hidden area mesh in Pitool?

**Comment by damien022** [comment]
To expand upon it, the flickering only appears with Motion Smoothing On (and PP on). If that is of any help?

**Comment by mbucchia** [comment]
Thanks for the details, I can reproduce and I'll be looking into it.

PS: Things like PP and smoothing are largely outside of my control in PimaxXR, all I do is read/write the flag to enable them :( I hope there is something I missed here.

**Comment by mbucchia** [comment]
I've been investigating quite a lot but no luck so far. 

I did find out that using the FOV override in OpenXR Toolkit and reducing the FOV by a few percent t removes the flickering. This isn't really a solution to the problem, but at least it's sending me a certain path to dig further.

**Comment by mbucchia** [comment]
Unfortunately I still do not have a solution to this problem. There are timing issues in the Pimax software, and I suspect this flickering is the result of these issues.

**Comment by mbucchia** [comment]
I have some good news I think: pimax shared a hidden option in PVR, that when used, seems to fix this issue. I will integrate in the next release.

**Comment by mbucchia** [comment]
Should be fixed by d75e9673e7182b6e425473c22170a98adf46e276.
