### ISSUE TITLE
cant start DCS in Pimax XR

### ISSUE THREAD

**Issue by Speed989** [mbucchia/Pimax-OpenXR#24]
when i start DCS i get a Err called "openxr cannot create dx texture swap chain:err -2" 
What can i do?

**Comment by Speed989** [comment]
Hi

It is now running i dont know what it was but now there is no more err.

Tank you

Matthieu Bucchianeri ***@***.***> schrieb am Fr., 23. Sep.
2022, 03:56:

**Comment by mbucchia** [comment]
I have seen issues like this before where restarting Pitool fixed it, and the error in PimaxXR was during a call to Pimax software.
