### ISSUE TITLE
No Longer works with 5K Super

### ISSUE THREAD

**Issue by GreggHHHHHH** [mbucchia/Pimax-OpenXR#26]
Just letting you folks know. It stopped working in the past couple days. If you need any info let me know. I can't use the capture trace because my bitdefender will go crazy again.

**Comment by mbucchia** [comment]
Can you elaborate what you did "past couple days"? Did you update PimaxXR? Pitool?

What does "it stopped working" means... error message? Log file?

**Comment by gregghanpeter** [comment]
It cannot function independently without SteamVR.

**Comment by mbucchia** [comment]
If SteamVR starts up, it simply means that you have accidentally configured SteamVR as your OpenXR runtime.

Open the PimaxXR Control Center app from your Start Menu and make sure PimaxXR is selected.

**Comment by mbucchia** [comment]
Would also be helpful if you provided any sort of details..
 What application you're using for example.

**Comment by GreggHHHHHH** [comment]
Yes I change it to Pimax in the program but it goes to SteamVR anyways. I am currently playing F1 22. The only thing that I cahnged in the main Pimax program is change the render quality of the game. I could try  changing it back but I don't think that would do me any good.

**Comment by mbucchia** [comment]
Your game F1 22 does not use OpenXR and require OpenComposite. Have you checked your install of OpenComposite? Beware that if you used the game DLL override, it gets overwritten every time your game is updated.

You can take a look at the log in PimaxXR (which I asked in my first reply to you). My guess is that log doesn't even get updated anymore, because your game isn't trying to use OpenXR.

**Comment by GreggHHHHHH** [comment]
I don't see any log folders in either install dir. I can try installing xr toolkit ans see what happens.

**Comment by mbucchia** [comment]
There is an open logs button in the PimaxXR Control Center app, please use that.

**Comment by GreggHHHHHH** [comment]
Yes. I looked in the log. Nothing there. It's blank. I also found the file in the Locak folder but nothing in it. I installed openxr toolkit and it works fine but no fix for pimaxxr so I uninstalled it as I don't have time for complicated hotkey combos when I have a headset on my face.

**Comment by GreggHHHHHH** [comment]
I'm going to quit messing with it.Everything else works fine. I ran Flight Simulator and pimaxXR prodused logs for that and it worked. PimaxXR more fuzzy than SteamVR but I don't get the juddering like in Steam.

**Comment by mbucchia** [comment]
Your issue is with OpenComposite, not PimaxXR. Closing.
