### ISSUE TITLE
crashes steamVR after few minutes

### ISSUE THREAD

**Issue by CMDRRoach** [mbucchia/Pimax-OpenXR#28]
first of all mbucchia your an absolut legend i finally made it past bonelabs Mainmenu - 00 loadingscreen thank you so much for that however a few seconds later my steamVR crashed on the previos version steamVR crashed right after starting bonelabs but atleast it hold a little bit longer this time

*update*: i tried again and noticed that the crash only happens sometimes after pressing the home button on index controllers

**Comment by mbucchia** [comment]
Oh right you should never press those Home buttons. They do cause a crash. Not too sure how I can avoid that.

**Comment by mbucchia** [comment]
Not actionable. Closing.
