### ISSUE TITLE
Messing up Quest 2 over VD somehow

### ISSUE THREAD

**Issue by Raging-Beard** [mbucchia/Pimax-OpenXR#29]
Even with it set back to SteamVR in the app, for some reason OpenXR games are unplayable now in my Quest 2 over VD. Steam shows it as XR runtime, but something must be wrong.

**Comment by Raging-Beard** [comment]
So Uninstalling PimaxXR fixed it. Despite PimaxXR being set to SteamVR, and Steam showing as much, this app was causing the issue with my Quest 2 over Virtual Desktop.

**Comment by Raging-Beard** [comment]
Oh damn, I didn't grab the log, sorry.

**Comment by mbucchia** [comment]
That sounds a bit unlikely to me. You can always confirm by checking the `ActiveRuntime` registry key at `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1`. This is the one and only system-wide change that PimaxXR does. There is nothing else that could interfere with SteamVR or VD.

**Comment by Raging-Beard** [comment]
Ok, I don't doubt you of course, but I'm not lying lol. It was the same yesterday and today, but worked as soon as I uninstalled PimaxXR.

**Comment by mbucchia** [comment]
I'm not saying that :) but with the exception of that one registry key, PimaxXR does nothing else to your system.

Can you describe what "causing the issue with my Quest 2 over Virtual Desktop" exactly means? Did VD not start? What about other apps not through VD but SteamVR directly?
Looking at the log would help to. For example deleting the log file. I expect no new log file will be created once you switch back to SteamVR.

**Comment by Raging-Beard** [comment]
I installed PimaxXR again and it broke again. Basically OpenXR games come up as a wonky out of place screen. However, uninstalling it didn't fix it this time. No idea what is going on, I have made no other changes.

**Comment by Raging-Beard** [comment]
I guess it was just a coincidence with PimaxXR it seems, as you say, couldn't be the cause anyway.

**Comment by mbucchia** [comment]
Uninstalling PimaxXR will not clear that registry key by the way, you will still need to do that manually through SteamVR's Developer setting.

**Comment by Raging-Beard** [comment]
Thanks, I think it's correct though, it says "
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\steamxr_win64.json"

**Comment by Raging-Beard** [comment]
It seems OpenXR is just broken for me in general, set to PimaxXR or SteamVR, it's broken.

**Comment by Raging-Beard** [comment]
So basically it seems than whenever I start an OpenXR game, it takes my headset height as the floor for some reason. As an OpenXR expert, any idea on how to fix this please? I uninstalled SteamVR, deleted SteamVR and steam/config folders, but no change. Thanks.

**Comment by mbucchia** [comment]
There should be a setting in SteamVR during Room setup for the height. Can't remember exactly. It's possible that going back and forth between your Pimax and Q2, that setting gets messed up and you need to redo room setup perhaps?

**Comment by mbucchia** [comment]
Also, to be clear, the room calibration isn't related to OpenXR. If it's bogus then it's an issue in the Valve or Oculus software.

**Comment by Raging-Beard** [comment]
I ran PiTool room setup, and height is better now, but I'm not in the right position. For example, if I load Phasmaphobia the utility belt is a few feet in front of me.
In the Quest 2 over VD my eyes are still on the floor.
OpenXR is a complete mess for me :(
Thanks for your input, I appreciate it's not what you're here for.

**Comment by mbucchia** [comment]
I've kinda lost track of what you are testing specifically with Pimax (SteamVR or PimaxXR?). With PimaxXR there is a "recenter at startup", doesn't that do what you need and ensure that you always start in a decent position?

It sounds to me that SteamVR is the issue, not OpenXR, which is not involved in the centering/floor height/room setup management. I would also recommend you try without VD and just Oculus to see what things look like there.

**Comment by Raging-Beard** [comment]
Sorry I will try to clarify... If I run an OpenXR game in either Pimax or Quest 2, doesn't matter which, the game puts my eyes at floor level. All OpenXR games run perfectly.

I have attached examples showing Vermillion, Brink Traveller, Phasmaphobia.

![floor3](https://user-images.githubusercontent.com/20541678/193513086-e35f39b8-be6f-489c-8264-b68dd73fe3ec.jpg)
![floor1](https://user-images.githubusercontent.com/20541678/193513092-05dda21f-f5dd-4fc3-99de-5315691fd4b5.jpg)
![floor2](https://user-images.githubusercontent.com/20541678/193513093-09e40604-d366-4589-a693-e3924acae05f.jpg)

**Comment by Raging-Beard** [comment]
It also does this using PimaxXR on Bonelab and Brink. So it can't be SteamVR related right?
Is OpenXR somewhere else, can I remove it and reacquire or download files again?
Thanks.

**Comment by mbucchia** [comment]
PimaxXR uses the floor height that you set up during Pitool/Pimax Client room setup.

There is no "OpenXR" being downloaded and installed. Your app is talking directly to either PimaxXR or SteamVR. There is no in-between component.

Can you try the following thing to determine what value Pitool/Pimax Client currently uses for floor height:

1) Make sure Pitool/Pimax Client is running
2) Open a command prompt (`cmd.exe`)
3) Run the following exactly as below:
```
"C:\Program Files\PimaxXR\pimax_cli.exe" -decimal eye_height
```

This will print the current floor height in meters. Would like to know what it says for you.

**Comment by Raging-Beard** [comment]
It says eye height =1.675

**Comment by Raging-Beard** [comment]
Also, if I put SteamVR back as the runtime, in Pimax it's mostly a black void, with a few pixels ahead in the distance. Looking up and down it shows a line of images in to infinity of what should be the game, much like looking at a roll of video film negative. Completely messed up basically.
With PimaxXR set, it's just the eyes at floor level issue, and this happens on Quest 2 over VD with SteamVR as runtime too.

**Comment by mbucchia** [comment]
I have no other inclination than to close this issue. The symptoms are shown system-wide with other devices, and therefore this is not a PimaxXR issue.
