### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by SEt-t** [mbucchia/Pimax-OpenXR#3]
It would be nice to have Vulkan support.

Now it's possible to hack D3D11->D3D12 and D3D12->Vulkan layers to make it kind of work, but this approach has several issues:
1) Layer loading order is important, won't work if chained the other way. And this order is defined by what? Full file name?
2) Obviously doesn't work on Win7 while it should be possible with direct D3D11->Vulkan.
3) Pimax creates swapchain textures with KMT sharing style, not NT-handles. So direct sharing is possible for D3D11->D3D12 and D3D11->Vulkan, but not D3D11->D3D12->Vulkan because D3D12 can only create shared NT-handles.

So, native support or at least direct D3D11->Vulkan layer would be much easier to use.

**Comment by mbucchia** [comment]
Last time I checked there wasn't really any Vulkan plus OpenXR app on the market. At least not something big enough to justify the time investment. What app do you need this for?

**Comment by SEt-t** [comment]
For our scientific application, not publicly available. For now I'm doing Vulkan->D3D11 interop myself but definitely would be cleaner to have pure Vulkan code.

**Comment by mbucchia** [comment]
That's an interesting use case, however this is a bit too much work for something that only a very very very small number of apps/users will benefit from.

Once a big title like DCS or X-Plane (think 10,000s of potential users) will come in the picture I will reconsider but right now it's just not doable.

You seem to have good knowledge and you saw my other projects for DX12 and Vulkan interop, if you want to contribute this code to the runtime I am more than happy to collaborate on a pull request.

**Comment by mbucchia** [comment]
After giving some thoughts, I am actually warming up to the idea of D3D12 support directly in the runtime. If that works well, I might do the Vulkan support too.

**Comment by mbucchia** [comment]
Good news, I will be committing both D3D12 and Vulkan built-in support later today! Previous work on the API layers made it really easy to port over.

**Comment by mbucchia** [comment]
Vulkan support was added in 3957b4540558dec1aed633c44aa1a27c35a8e8c2.

General reminder about Vulkan + OpenXR support: it is critical to use `XR_KHR_vulkan_enable2` and not the original `XR_KHR_vulkan_enable` extension, which was flawed. Applications written on the old extension will not be portable with PimaxXR (they may or may not work depending on the GPU/driver).
