### ISSUE TITLE
v0.2.8 wont switch back to SteamVR

### ISSUE THREAD

**Issue by scud68** [mbucchia/Pimax-OpenXR#30]
Each time I select SteamVR as the OpenXR runtime, if I close down the window and then re-open it, it has gone back to PimaxXR runtime

**Comment by mbucchia** [comment]
Are you getting an error message? Are you sure Windows is letting the app run as administrator? Can you try force running as administrator (right click on icon, then run as administrator).

**Comment by scud68** [comment]
Sorry for the delay getting back to you. Yes – I am running the program as administrator and the problem persists. No – there are no error messages. When I select SteamVR version as the openVR runtime, then close the app down. As soon as I re-open it, it has gone back to PimaxXR. Regards, Sent from Mail for Windows From: Matthieu BucchianeriSent: Saturday 8 October 2022 21:43To: mbucchia/Pimax-OpenXRCc: scud68; AuthorSubject: Re: [mbucchia/Pimax-OpenXR] v0.2.8 wont switch back to SteamVR (Issue #30) Are you getting an error message? Are you sure Windows is letting the app run as administrator? Can you try force running as administrator (right click on icon, then run as administrator).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mbucchia** [comment]
Unfortunately, I do not have a way to investigate this without an error message. No one else has reported such issue.

I suggest you use the manual way to revert to SteamVR:

https://github.com/mbucchia/Pimax-OpenXR/wiki/Reverting-back-to-SteamVR#manual-method
