### ISSUE TITLE
black screen on Automobilista 2

### ISSUE THREAD

**Issue by Gonzas74** [mbucchia/Pimax-OpenXR#32]
im having a issue with Automobilista 2 using 
Pimax-OpenXR 0.28 and opencomposite menus are ok, but as soon as i press drive all is black, no user interface just sound and if i go direcly to race, i can only see the starting lights.

same image on the 8kx and on the monitor

thanks!

**Comment by Gonzas74** [comment]
seems that going from SMAA to MSAA fixed it

**Comment by mbucchia** [comment]
Thank you, I will have to look at what difference this setting makes.

**Comment by y2kfred** [comment]
Hello,
here some infos:

 Pimax 8kx 75Hz

Windows 11 Pro 22H2

Nvidia 527.37


PiTool
- latest updates
- FFR off
- FoV Normal
- Render Quality 1
- Parallel reporjection on

PimaxXR
- 0.28
- OpenXR enabled

OpenXR
- latest with toolkit
- openVr toolkit working ingame (Overlay is usabel)


Automobilsta2
- None, MSAA, SMAA, FXAA all the same
- Menu is working on VR
- no error
- Supersampling 1.5 in VR


Started direct after reboot from PITOOL
Direct started a test drive single player

LOGFILE

[OXRTK] 2022-12-01 20:49:55 +0100: OpenXR Toolkit - GA-2 (v1.2.2)

[OXRTK] 2022-12-01 20:49:55 +0100: dllHome is "C:\Program
Files\OpenXR-Toolkit"

[OXRTK] 2022-12-01 20:49:55 +0100: OpenXR-Toolkit layer is active

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_D3D11_enable

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_D3D12_enable

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_vulkan_enable

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_vulkan_enable2

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_opengl_enable

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_composition_layer_depth

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_win32_convert_performance_counter_time

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_KHR_visibility_mask

[OXRTK] 2022-12-01 20:49:55 +0100: Runtime supports extension:
XR_FB_display_refresh_rate

[OXRTK] 2022-12-01 20:49:55 +0100: XR_EXT_hand_tracking is not available
from the OpenXR runtime or any upsteam API layer.

[OXRTK] 2022-12-01 20:49:55 +0100: XR_EXT_eye_gaze_interaction is not
available from the OpenXR runtime or any upsteam API layer.

[OXRTK] 2022-12-01 20:49:55 +0100: Application name:
'OpenComposite_AMS2AVX', Engine name: ''

[OXRTK] 2022-12-01 20:49:55 +0100: Detected OpenComposite

[OXRTK] 2022-12-01 20:49:55 +0100: Using OpenXR runtime PimaxXR
(Unofficial) 0.2.8

[OXRTK] 2022-12-01 20:49:55 +0100: --> aSeeVR_connect_server(5347)

[OXRTK] 2022-12-01 20:49:57 +0100: <-- aSeeVR_connect_server -1

[OXRTK] 2022-12-01 20:49:57 +0100: HAGS is on

[OXRTK] 2022-12-01 20:49:57 +0100: Using OpenXR system Pimax Vision 8K X
(aapvr)

[OXRTK] 2022-12-01 20:49:57 +0100: Upscaling from 2854x2370 to 3804x3160
(133%)

[OXRTK] 2022-12-01 20:49:57 +0100: Unsupported graphics runtime.

[OXRTK] 2022-12-01 20:50:00 +0100: Using Direct3D 11 on adapter: NVIDIA
GeForce RTX 3080

[OXRTK] 2022-12-01 20:50:00 +0100: Early initializeInterceptor() call

[OXRTK] 2022-12-01 20:50:00 +0100: MipMap biasing for upscaling is: -0.830

[OXRTK] 2022-12-01 20:50:01 +0100: Open menu with CTRL+NACH-UNTEN

[OXRTK] 2022-12-01 20:50:01 +0100: Creating swapchain with
dimensions=1920x1080, arraySize=1, mipCount=1, sampleCount=1, format=29,
usage=0x31

[OXRTK] 2022-12-01 20:51:08 +0100: Creating swapchain with
dimensions=2856x2372, arraySize=1, mipCount=1, sampleCount=1, format=29,
usage=0x31

[OXRTK] 2022-12-01 20:51:08 +0100: Creating swapchain with
dimensions=2856x2372, arraySize=1, mipCount=1, sampleCount=1, format=29,
usage=0x31

[OXRTK] 2022-12-01 20:51:08 +0100: Creating swapchain with
dimensions=1920x1080, arraySize=1, mipCount=1, sampleCount=1, format=29,
usage=0x31

[OXRTK] 2022-12-01 20:53:35 +0100: D3D11Device destroyed

[OXRTK] 2022-12-01 20:53:35 +0100: Session destroyed


I made a photo from my screen, in the VR headset it looks the same

Do you need any more info?

Best regards

**Comment by y2kfred** [comment]
So i have an update, trying different combinations for some hours:  

using the OpenXR Toolkit FFR (any setting but off) cases the black screen- no matter what Automobilista graphic settings.

So don't use it and anything is ok - I turned on FFR in the Pitool, thats ok.

Other finding: Pitool 283 and 284 have problems with parallel reprojection. 277 workes fine for me.

br

**Comment by y2kfred** [comment]
Hello,
another update. Seems the issue is still here. 
On first start of ams the track is nearly black expept game overlays. On second start of am2 to is works.
bg

**Comment by mbucchia** [comment]
Tried various settings and cannot reproduce any of the issues described above.

As for SMAA, it always reverts to Off in my configuration :(

I only have the Demo version of the game, and there is not much else I can do at this point.
