### ISSUE TITLE
Elite Dangerous works (Horizons 3.8/4.0 & Odyssey)

### ISSUE THREAD

**Issue by AndreasUK** [mbucchia/Pimax-OpenXR#33]
Elite Dangerous (all versions) works per:
PimaxXR: Yes
OpenXR Toolkit: Yes
Need OpenComposite: yes
Need Parallel Projection: yes

On Pimax (PiTool scale 1.0, Normal View) using OpenComposite, PimaxXR and OpenXR Toolkit (basic modes, unscaled), shows a running resolution of 3840x3160 against SteamVR's 100% resolution (same PiTool setting) of 4620x3948. That's 12.14MP (PimaxXR) vs 18.24MP (SteamVR) with associated performance increase without issues. The Pimax-OpenXR (PimaxXR) looks better.

**Comment by mbucchia** [comment]
Thanks! Added to Compatibility page.
