### ISSUE TITLE
Acc menus to close 

### ISSUE THREAD

**Issue by Exiledslinky** [mbucchia/Pimax-OpenXR#36]
Fresh install but the in-game menus are to close and unreadable.   Changed the json file to make them farther and bigger.   But no luck.

**Comment by mbucchia** [comment]
I'll try the game later, bur tbh this isn't something PimaxXR has control over. Game says to display many at a specific location/size. PimaxXR just does what it's told to do. Perhaps an issue with OpenComposite?

**Comment by 3NPV5IRR** [comment]
@Exiledslinky Try to use Pitool v1.0.1.277 instead of Pimax Store application.

**Comment by cloutierpo** [comment]
On my side, menu and HUD is correct, but they're ''moving'' when I play. Using SteamVR, if I move my head I can focus on some parts of the HUD. It's fixed in the image. Using PimaxXR, if I turn my head right, HUD kind of move to the left... Pretty annoying because otherwise the game run so much better

**Comment by mbucchia** [comment]
> On my side, menu and HUD is correct, but they're ''moving'' when I play. Using SteamVR, if I move my head I can focus on some parts of the HUD. It's fixed in the image. Using PimaxXR, if I turn my head right, HUD kind of move to the left... Pretty annoying because otherwise the game run so much better

That's a bug in the Pimax software since Pitool 281. I have reported it to Pimax already, but given how slow the progress is, I am putting a workaround in PimaxXR.

**Comment by cloutierpo** [comment]
> > On my side, menu and HUD is correct, but they're ''moving'' when I play. Using SteamVR, if I move my head I can focus on some parts of the HUD. It's fixed in the image. Using PimaxXR, if I turn my head right, HUD kind of move to the left... Pretty annoying because otherwise the game run so much better
> 
> That's a bug in the Pimax software since Pitool 283. I have reported it to Pimax already, but given how slow the progress is, I am putting a workaround in PimaxXR.

At least now I know where it comes from. Thank you!

**Comment by mbucchia** [comment]
All the issues described on this ticket are bugs in Pimax software, there is nothing I can do on my end.

Closing.
