### ISSUE TITLE
No Chaperone/Guardian

### ISSUE THREAD

**Issue by gradyg21** [mbucchia/Pimax-OpenXR#39]
Hey mate,

Great work on this. Happy to have a workable Bonelab solution. Shame that this game appears to be busted for good on SteamVR, neither Pimax nor WMR seems to work. I had to switch my buddy's HP Reverb G2 to use the WMR OpenXR implementation too. 

I just have one issue, and that's no guardian in PimaxXR. It makes Bonelab pretty scary, as I don't have a large room for VR. Is there anyway to add a guardian feature to PimaxXR? Even a ring on the ground would be a big step. I feel properly blind as it is now. I also can't use a rug or a mat in this space either, so I'm reliant on software. Thanks for all the work already!

-Grady

**Comment by mbucchia** [comment]
This is a pretty huge task. I like the idea of keeping it simplistic though, and a very basic system would certainly be worth the effort (going from 0 to "something"). I'm not really sure it will be possible to draw a ring with correct depth perception on top of the app though. Will need to try.

**Comment by mbucchia** [comment]
Looking at this now. How do you suggest placing the center of the ring though? I suspect this is something people want to recalibrate at the beginning of their game session.

I was looking to use the controllers system button (mike intercept system+trigger to recenter), but unfortunately it looks like that just starts SteamVR which is really bad

**Comment by gradyg21** [comment]
Hey Matthieu, 

Shame that the system buttons are just SteamVR launchers. Always seemed strange to me that BOTH the left and right system buttons on Index controllers are for SteamVR's menu, which means one of the face buttons has to be for the game's pause menu. Oculus's system of one Oculus menu button, one in game pause button seems so much smarter.

As a suggestion, what about just a button in the desktop app? Put your headset down on the floor where you'd like the ring to be, set the ring radius in meters or feet, and get to playing? 

Considering we're talking about headsets with lighthouse tracking, seems unlikely that it should need to be changed too often, as long as the ring stays put between play sessions.

SteamVR doesn't seem to have an issue holding the guardian exactly in place, likely because the lighthouses don't ever move. My Quest 2's guardian shifts around a surprising amount.

As another spit-ball idea, is there anyway to access the existing guardian data from SteamVR, and 'import' the measurements, or at least the centre of the room?

**Comment by gradyg21** [comment]
Here's a dumber, much worse idea: voice commands to recenter the ring

**Comment by mbucchia** [comment]
For some reason, I can't reproduce that behavior where the system button on Index made SteamVR start up... so using the button is back on the table.

> As a suggestion, what about just a button in the desktop app? Put your headset down on the floor where you'd like the ring to be

I had somehow not though of the "put your headset down" so I kept thinking that a button in desktop app was impossible if you are away from your keyboard/mouse. But this is a good idea in fact.

> set the ring radius in meters or feet, and get to playing?

Yes a slider for radius is definitely what I had in mind.

> As another spit-ball idea, is there anyway to access the existing guardian data from SteamVR, and 'import' the measurements, or at least the centre of the room?

It's possible but much more complicated.

Thanks for the ideas!

**Comment by gradyg21** [comment]
No worries! Hope I could help a bit! I look forward to seeing what you come up with.

**Comment by mbucchia** [comment]
I still need to see the feasibility for rendering the ring, but I think I had an idea to do that.

**Comment by gradyg21** [comment]
Excellent! Good luck!

**Comment by mbucchia** [comment]
Added basic playspace boundaries system 98c9875806238d9dfce905c8fff3ca0222475b1e with customizable radius and display threshold. Added re-centering control in 4e58ee3ddc93a442dacb8937689df39e694b2578.

Note: to disable the controller's system button (so they can be used as hold System+Trigger for 2s to recenter), follow these: https://community.openmr.com/t/solution-disable-steamvr-start-on-controller-power-on-or-system-button-press/30393.

**Comment by gradyg21** [comment]
Hey Matt, good work! I'll give this a test tonight!

I followed your link, and looks like Sweviver says in that forum that Pimax Experience should disable the system buttons automatically, so for most Pimax owners this should be done already. I assume most Pimax owners have Pimax Experience?

**Comment by gradyg21** [comment]
Hey my friend, sorry if this is a dumb question but I'm not experienced with GitHub. The current release, 0.2.8, says from Oct 1. Next to that, it says there have been 23 'commits to main' since this release. Clicking on that, I can see the guardian features. If I understand correctly, those are not in the release install as of now? Do I need to build from the code, if such a thing is possible?

**Comment by mbucchia** [comment]
Yes the new code isn't in an official release yet. I wouldn't recommend that you build from code if you don't have experience.

Most likely will not have the time to make a release this year due to the holidays.

**Comment by gradyg21** [comment]
No worries! I found the setup artifact under the latest action for the commit. Maybe I know a bit more than I thought! I installed that, yet to test it. I know it could be buggy or completely broken, and will make no complaints if it doesn't work properly. But for now, I will enjoy my 'beta' 0.2.9 release! Do you want feedback on issues, or should I wait until a proper release?

**Comment by mbucchia** [comment]
Hey, It's ok for you to use that build. I was going to share it eventually once I did a little more testing. Not sure what you can expect from it :) the guardian stuff should be fairly solid, but there are 2 other changes in there that I am less confident with (Index controller finder sensing support and more importantly upgrading to the newer Pimax SDK).

Please report issues you might observe.

FYI for the guardian, there are 4 ways you can recenter it:
- It is recentered at start up if you check "Recenter at start up" in the Control Center app
- You can use the keyboard: hold Ctrl+Alt+Space bar for ~2 seconds to recenter the view (which also recenters the guardian)
- You can use Vive Controller: hold either System+Trigger or Menu+Trigger for ~2 seconds
- You can use Index Controller: hold System+Trigger for ~2 seconds

Note that your game will still see the corresponding input (eg: Space bar or controller Trigger).

If System button opens SteamVR, please do the trick here: https://community.openmr.com/t/solution-disable-steamvr-start-on-controller-power-on-or-system-button-press/30393. AFAIK it is not done automagically when installing Pitool.

You can go in the Control Center to set up the guardian radius (the actual radius of the playspace) and its visibility threshold (at what point the guardian becomes visible). These values can be changed while a game is running, you don't need to restart the game.

For example, you can set a guardian of 2 meters radius so you have 2 meters (measured in floor distance, does not use the height) to move in all directions and have a threshold at 1.5m to have the guardian display when you only have 50cm left.

**Comment by gradyg21** [comment]
Perfect, all looks good. This is seeming more and more official by the update. Happy to have (progress on) index finger tracking! I miss it in games that don't have it.

**Comment by gradyg21** [comment]
![Screenshot 2022-12-23 155500](https://user-images.githubusercontent.com/26560257/209411866-86101fcc-a729-45bd-a2ad-ee0290797161.png)
![Screenshot 2022-12-23 155817](https://user-images.githubusercontent.com/26560257/209411867-b26a234d-4f85-4a26-be7b-f37aeef9559e.png)
For what it's worth, Pimax Experience did automatically change this setting for me. If you haven't used Pimax Experience, it is not the same as Pitool. PE is Pimax's VR launcher software, that you use in VR. It's not the desktop interface. I don't think PE is included automatically anymore, but it was for a while, and it does automagically change that setting.

**Comment by mbucchia** [comment]
Thanks for the great feedback! How was the Index in Bonelab btw? I know there's a lot of discussions about offsets, which feel fine to me honestly.

**Comment by gradyg21** [comment]
I will be trying tonight! Haven't had time to throw on the headset yet since Wednesday, but I'll let you know how it all works once I have!

**Comment by gradyg21** [comment]
I have come across an issue. Ring looks good and is working properly, BUT: for my space, 1 meter radius is a little large in one direction. My space would properly JUST hit 2m across, so the farthest parts of the circle are over top of furniture in some spots. being able to set less than 1m radius is necessary for me. This is ESPECIALLY true for visibility distance, as 1m means I only see the ring once I've walked into my desk. 

Is there a way I can change these in a config file? Seems like decimals are supported. The box that shows the distances looks like a text field isn't, so can't change it there. 

Index finger tracking works pretty well! Pinky, ring, and middle, all work properly. Only oddity is simply touching my index (haha) finger down to the trigger shows that finger as curled all the way in game. Ideally, the finger will curl slightly on trigger touch, and continue to curl as the trigger is squeezed. But this is much better than before!

**Comment by mbucchia** [comment]
What is the ask? Allow radius/threshold under 1m?

**Comment by gradyg21** [comment]
Yes please! Should have simplified my comment aha.

**Comment by mbucchia** [comment]
Cool yes easy peasy. If you go to the registry under `HKLM\Software\PimaxXR` you can already do that (the value there is in cm I think, so 100 for 1m). I can then lower the limit in the UI for the next build.

**Comment by gradyg21** [comment]
Perfect! To clarify guardian_threshold is the distance for visibility, and radius is the ring?

**Comment by mbucchia** [comment]
Yes this is correct.

**Comment by mbucchia** [comment]
Also, my bad I just peeked at the code and value is in fact in mm not cm, so add one 0.

**Comment by gradyg21** [comment]
No worries! I saw the current value was 1000 so I figured it was MM

**Comment by gradyg21** [comment]
Also, index controllers seem to be working properly with swap grip/aim turned OFF. Offsets were high with the setting off, but all seems good with them off! If that’s intended, good work! If it’s a fluke, that’s fine too haha!

**Comment by mbucchia** [comment]
Yes the swap option was mostly to solve issues with OpenComposite. Shouldn't be needed with Bonelab and plain OpenXR apps.

**Comment by mbucchia** [comment]
> Only oddity is simply touching my index (haha) finger down to the trigger shows that finger as curled all the way in game. Ideally, the finger will curl slightly on trigger touch, and continue to curl as the trigger is squeezed.

I just got back and pay attention to it. It is indeed a little bit weird. I have to see if this is something I can fix (right now I am just returning the data as-is, and index finger works the exact same way as the others, so I'm not sure why it's extra curly).

**Comment by mbucchia** [comment]
I checked Bonelab on a Vive with Index controller (and so with SteamVR OpenXR), and the weird index finger behavior is there too. So I assume at this point, this is a game bug, nothing I can fix.
