### ISSUE TITLE
Is the PimaxXR compatible with PiPlay?

### ISSUE THREAD

**Issue by albertowd** [mbucchia/Pimax-OpenXR#41]
## Disclaimer

I'm asking this because I have a Pimax4K that works with DCS and MSFS 2020 great with PiTools (.284) and PimaxXR (.2.8).
But, the generated image, at least for me, is slightly choppier than the PiPlays old software (3.0.0.85), but with it I cannot run any of those games.

Has anybody tried it before?

This is not a feature request (unless more people could ask for it) and it's not a bug, I think, because the PiPlay software is for old headsets and it's not supported anymore, but the Pimax4k has many bugs on the new drivers (lacks the horizontal calibration and a proper IDP screen adjust)....

Btw, thanks for any help!

## Not Working

Doesn't event start, MSFS 2020 does not detect a HMD.

## Already Tried

* Restart the HMD
* Restart the service (the software itself, the service I don't know how, there is a button on PiTools but not on PiPlay)
* Change the rendering scale

## PimaxXR Log with PiPlay 3.0.0.85

2022-12-05 08:46:59 -0300: PimaxXR - v0.2.8
2022-12-05 08:47:00 -0300: xrGetInstanceProcAddr: pvrResult failure [4]
    Origin: pvr_initialise(&m_pvr)
    Source: D:\a\Pimax-OpenXR\Pimax-OpenXR\pimax-openxr\instance.cpp:127
2022-12-05 08:47:00 -0300: xrGetInstanceProcAddr failed with XR_ERROR_RUNTIME_FAILURE

**Comment by mbucchia** [comment]
I dont know about Piplay, but given the error (the very first call to the Pimax SDK failing), I'm going to guess that Piplay uses and completely different way to communicate with the headset, and is not supported.

**Comment by mbucchia** [comment]
Given the log it looks to me that it's not compatible at all. Does Piplay install a `libpvrclient64.dll` on the system?

**Comment by mbucchia** [comment]
Oh nevermind, looking at the definition of error 4: "interface not found", it would imply there is a libpvrclient but it's just too old and does not implement the necessary interface for PimaxXR.

**Comment by mbucchia** [comment]
Not actionable.
