### ISSUE TITLE
Vive Controller in X-plane11/12

### ISSUE THREAD

**Issue by christianhbeck** [mbucchia/Pimax-OpenXR#42]
Hello,

thank you very much for this nice software. I have tried PimaxXR with my Artisan head set in X-plane11/12 and I get a substantial performance improvement. I operate the cockpit exclusively with a joystick and a Vive wand. For tracking I use Lighthouses. 

Unfortunately, the trigger button is not transmitted into X-plane. The trigger button is instead mapped to a joystick axis. Also the touchpad button is not transmitted to X-plane. Unfortunately, this makes PimaxXR unusable for me. I have tried the options for controller emulation. While xplane displayed a different controller, the button mapping was still missing. 

I would appreciate a fix a lot. If there is any further information required to help fixing this problem I am more than happy to support.

**Comment by mbucchia** [comment]
The bad controller mappings is a known issue of OpenComposite, nothing I can do in PimaxXR. Please ask the OpenComposite developers to fix it.
