### ISSUE TITLE
DCS freezes on open

### ISSUE THREAD

**Issue by plaughlin7** [mbucchia/Pimax-OpenXR#47]
DCS last update open XR is now native. I can not open in VR anymore it just freezes at trying to launch DCS

**Comment by mbucchia** [comment]
Works fine for me.

> ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.

**Comment by plaughlin7** [comment]
I wonder what is wrong with mine. Everything worked fine in DCS open beta until the last update with native Open XR. Now it just freezes on start. I can not even get to the start menu in safe mode to go back to defaultSent from my iPadOn Jan 26, 2023, at 10:52 AM, Matthieu Bucchianeri ***@***.***> wrote:﻿
Works fine for me.

ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.
