### ISSUE TITLE
xrWaitFrame: pvrResult failure [-1]

### ISSUE THREAD

**Issue by Jongraham123** [mbucchia/Pimax-OpenXR#50]
**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**

**Describe the bug**

_A clear and concise description of what the bug is._
_Always attach (upload, do not copy/paste) the log file that can be found at `%LocalAppData%\pimax-openxr\logs` or opened from the PimaxXR Control Center app._

**Environment**

- _Application/Game and version_: 
- _Version of Pitool or Pimax client_: 

**To Reproduce**

_Steps to reproduce the behavior:_

1. Run '....' game
2. Enable option '....'
3. See error

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Comment by mbucchia** [comment]
This is already fixed in the next version that will be released at TBD date.

Thanks.

**Comment by Jongraham123** [comment]
Hi, I am trying to get the best fps for DCS. I download Open Composite and PimaxXr.  - I have an issue when loading some modules and Multiplayer.  The Huey and the mig 29 work like a dream, but the more complicated ones crash when they hit the pre-loading world stage.  This also happens with all of multiplayer. The crash happens when you spool in and the world starts to draw.

**Comment by Jongraham123** [comment]
Wow... I didn't even write the bug yet. 😮
