### ISSUE TITLE
Uncontrolled graphics after a short interruption of the view to Lighthouse

### ISSUE THREAD

**Issue by y2kfred** [mbucchia/Pimax-OpenXR#51]
**Describe the bug**

I use the Pimax seated with ONE HTC Lighthouse, a monitor is in between the two.
I am starting iRacing from PiTool, OpenXR starts. Then you have to go to iRacing UI to select a game.
Then I put on the HMD.
If I am fast enough and the HMD has line of sight to the Lighthouse before iRacing starts everything is ok and stays stable
BUT
OF the HMD looses LOS for only a short the the picture collides and there is no way to recover. I have to kill the exe and restart the game. Colliding picture means oncontrolled rotation like moving my head 360 degree per secound. 

Expected: 
So maybe you say "your fault" with this setup, maybe thats true - however in 0.30 a recovery works -> HMD goes black and the correct picture stream came back after 2-3 seconds.
It seems 0.32 has a problem with tracking signal losses / recovery.

**Environment**

Pimax-OpenXR 0.32
PiTool 1.0.1.280 or .284 (FoF Normal, FRR conservative, Hitten Area Mask)
Windows 11
Nvidia 4090 latest driver
Pimax 8kx 2.1.255.299
iRacing

Thank you and keep on the great work

**Comment by y2kfred** [comment]
Addition:
I installed 0.30 for testing.
When the HMD looses the tracking to Lighthouse ist gets dark + monitor mirror gets white. BUT when the HMD to Lighthouse LOS is back the picture and tacking recovers without any problem.
So i stay on 0.30 right now.

**Comment by y2kfred** [comment]
Hello,
sorry to say but 0.3.4 doesn't work at all for me. Now the monitor shows fast moving pictures all the time and the HMD (pimax 8kx) stays black,
Nothing else changed, tried to start iRacing.

So back to 0.3.0 for me.

**Comment by mbucchia** [comment]
I haven't tested iRacing specifically but people had no issues in DCS, MSFS and Bonelab. I'll spin up iRacing later.

**Comment by mbucchia** [comment]
I tested iRacing now, with PimaxXR 0.3.4 and Pimax client 1.10. I had no issues, the experience was extremely smooth.

I did attempt to reproduce the loss of tracking, and indeed there is an issue there. But then I tried in 2 other OpenXR applications, and no issue there. So the bug is in iRacing. It's probably that older PimaxXR version did not report loss of tracking and therefore did not trigger the bug in iRacing. I'll have to put a workaround specifically for iRacing.

**Comment by y2kfred** [comment]
Hello,
thanks for testing. I can confirm that there are no issues in other OpenXP applications with 0.3.2 and 0.3.4.
What has changes since 0.3.0? This version always works - if tracking is lost HMD first gets black and then HMD picture recovers a few seconds after tracking signal recoverys (line of sight is back again to Lighthouse). No performance issues after that, very stable.

**Comment by mbucchia** [comment]
In 0.3.2 I made the runtime conformant to OpenXR standard to the letter, which means specific error/state signaling. I think one of these states is confusing iRacing. They had a similar bug with Varjo a few months ago. I'll have to find specifically which flag and either revert that change or make a quirk just for iRacing.

**Comment by mbucchia** [comment]
I reconfirmed today that this is 1000% a game bug, and the mistake PimaxXR is making is to actually do the right thing. Sucks,

Well anyway, I added a workaround here: 4c43b5828a616814bdd6d99ed4673cbc3a01c811.

**Comment by mbucchia** [comment]
Please try the new release 0.4.0.
