### ISSUE TITLE
games that worked with pitool 281 and PimaxXR 0.3.4 no longer work with Pimax client 1.1

### ISSUE THREAD

**Issue by Smeghead277** [mbucchia/Pimax-OpenXR#55]
I've recently tried out pimax client as I've been having tracking issues with pitool 281, however since the change over three games which previously worked no longer do.
These three all  require open composite so I aplogise if I'm asking for help in the wrong area.

with pimax client and PimaxXR 0.3.4 and opencomposite (sorry can't find version number, 64bit dll as of13/05/2023)

AsettoCorsaComp : on running it just goes to black screen and must be forced closed.

rFactor2: loads into menu but freezes when you press the "start racing" button (normally would load track and then enter session)

Automobilista 2: loads into menus and will load tracks and cars etc but then freezes when it should go into the race session.

I have attached log and trace for all 3 applications.
I am using pimax 5k plus with geforce 4080

Thanks in advance for any assistance.

[rFactor2.zip](https://github.com/mbucchia/Pimax-OpenXR/files/11468663/rFactor2.zip)
[Automobilista 2.zip](https://github.com/mbucchia/Pimax-OpenXR/files/11468666/Automobilista.2.zip)
[ACC.zip](https://github.com/mbucchia/Pimax-OpenXR/files/11468667/ACC.zip)

**Comment by mbucchia** [comment]
Thanks, haven't tested anything OpenComposite in a while.
I appreciate that you included traces for all 3.

I have ACC and AMS2 (Demo), so I'll see if I can do something from the traces and trying those games myself.

**Comment by mbucchia** [comment]
ACC and AMS2 both working at 86731193f0b89156c3c7bb130a2ab3d10a23814a.

**Comment by mbucchia** [comment]
Please try the new release 0.4.0.

**Comment by despinoza22** [comment]
i have the same issue with crystal

ACC with opencomposite via pimaxXR crash when i start a race, sometimes i can get in race and all goes well until i leave the race and then crash (9 out of 10), but openxr via steamvr works fine everytime
Tried 0.40
