### ISSUE TITLE
Failed to launch Minecraft in VR mode using PimaxXR runtime.

### ISSUE THREAD

**Issue by gilesabc** [mbucchia/Pimax-OpenXR#56]
**Describe the bug**

I can launch Minecraft in VR mode on SteamVR runtime, however, when I switch to PimaxXR runtime it can not enter VR mode.

**Environment**

Minecraft for Windows: v1.19.83
Pimax client: v0.3.4 

**To Reproduce**

Follow the steps on [https://help.minecraft.net/hc/en-us/articles/360057619052](url)

**Comment by mbucchia** [comment]
Thanks, I am aware of this and looked into it a while ago, however I have low confidence it is fixable. 

Minecraft is one of very few applications using UWP app containers, which is a special secure type of application intended to prevent certain less secure code to be used. It's an atrocity of Windows that fortunately not many applications chose to use.

To make this work with PimaxXR requires to find the magic incantation needed to establish a secure communication channel between PimaxXR and pi_server. I have no clue what that magic incantation is, and the public documentation is extremely not helpful. It might even be possible that pi_server needs to be changed, which is out of my control.

When using SteamVR, the communication is done between the SteamVR runtime and vrserver, both of which somehow perform the magic incantation.

**Comment by gilesabc** [comment]
Thanks for the reply!

**Comment by mbucchia** [comment]
Closing since I don't have a way to fix this.
