### ISSUE TITLE
EAC blocking PimaxXR software, "Untrusted system file"

### ISSUE THREAD

**Issue by xracecar** [mbucchia/Pimax-OpenXR#58]
After realizing that Pavlov VR had a new update, I had wanted to play but was blocked due to the fact that they made it run in OpenXR. From past experiences with BoneLab I installed PimaxXR to help with the issue to let me play, but the game tosses up a message showing "Untrusted system file" as such 
![eac untrusted system file](https://github.com/mbucchia/Pimax-OpenXR/assets/26825891/8686d32f-c186-45e6-afc3-a78819d303c1)

Pavlov VR Update 29 is the most recent update as of today.
Pimax is version 1.11.00.01 running on the Pimax Artisan

To reproduce what is happening, all you need to do is install PimaxXR on your system and have it running when you open Pavlov VR. A prompt saying that there is an untrusted system file will pop up while the game closes itself out.

What I was expecting was to be able to play with fairly small issues (such as hand tracking may be out of place as that's how it is in BoneLab) but with nothing really going to hinder my session.
[pimax-openxr.log](https://github.com/mbucchia/Pimax-OpenXR/files/11730627/pimax-openxr.log)

**Comment by mbucchia** [comment]
This is Pimax's fault. They aren't signing their own software. 

In the meantime, I provided a workaround here: https://github.com/mbucchia/Pimax-OpenXR/wiki/Signed-Pimax-client-DLLs

But as you'll note, I haven't put a DLL for 1.11, because it's difficult to keep up with the new releases. I'll try to add the 1.11 one later this week, meanwhile you can downgrade to 1.10 (or maybe try the 1.10 DLL with 1.11, but I'm not quite sure it'll work).

**Comment by xracecar** [comment]
Alright so the 1.10 DLL works perfectly fine, just needs some fine-tuning on PavlovVR's part, but thank you so much for pointing me in the right direction! My only issues are either related directly to how PavlovVR is taking inputs as their Index control scheme has been kicked out of the door, or to how the game senses that they are WMR controllers (I have it set to emulate the Touch controllers). I don't know if you have anything to say on that as PavlovVR just updated today, but just wanted to let you know that's happening.

**Comment by mbucchia** [comment]
Good to know the DLL works. I'm a bit surprised you are having bindings issue because Unreal Engine is usually pretty good with that. Have you tried not using the controller profile override in the Control center app (setting it to nothing)? Really that option was meant for Bonelab prior to me adding proper finger sensing support for Index, and that option should really not be needed. I'm actually considering removing it.

**Comment by xracecar** [comment]
The controller profile override set to nothing works properly, the controllers are sensed as Index controllers with the default bindings. Menus open, sprint sprints, scoreboard shows up. 

There also seems to be an old issue mentioning positional and rotational offset and that seems to be happening here in PavlovVR. Would it be better to make a new issue or to keep it in this thread?

**Comment by mbucchia** [comment]
> There also seems to be an old issue mentioning positional and rotational offset and that seems to be happening here in PavlovVR

I don't understand what you mean by "and old issue". The offsets for the Index controller in PimaxXR pass the conformance usability testing, and therefore are correct. If they don't seem right then it is likely an issue with the game, and nothing I can do about.

I have Pavlov on a different PC so I'll give it a try later.

**Comment by mbucchia** [comment]
You should 100% NOT be using the swap option. That option was meant to workaround OpenComposite bugs, and it will be removed.

The controller poses for Vive and Index are working in several apps as of today, so what you are saying really sounds like the game itself is broken. 

What type of physical controller do you actually have?

**Comment by mbucchia** [comment]
I tested the game and I understand what you mean "gun facing down".

One thing that is interesting is that the aim in the main menu is perfect. I think it's a combination of how the game uses the motion controller and the finger sensing of the Index. I'll have to look into why this happens, it still very much looks like a game issue to me, but we can probably workaround it

**Comment by mbucchia** [comment]
Setting `grip_pose_rot_x` to 40 in the PimaxXR advanced settings to override the game poses is fixing the issue. This isn't good. I'll continue trying to understand why this is happening.

**Comment by mbucchia** [comment]
Sorry for the delay, I'm looking at this now and checking the offsets for all controller types in all the games I own.

**Comment by mbucchia** [comment]
I have spent now 3 hours on this. The game is 100% at fault. Using offsets that make Pavlov VR work with Index Controller is 100% breaking both the OpenXR Conformance test suite and every other game like Beat Saber...

**Comment by mbucchia** [comment]
I'm seeing there is a "Gun Offset Adjust" option in the game. This will be your best bet until the developer fixes the game :(

**Comment by mbucchia** [comment]
Please try the new release 0.4.0.

 I adjusted the offsets a little. They are still not 100% correct in Pavlov but this is the game's bug. They are now in range of what "Gun Offset Adjust" can deal with.
