### ISSUE TITLE
Half Live Alyx Controller issue with PimaxXR

### ISSUE THREAD

**Issue by Fanta476** [mbucchia/Pimax-OpenXR#63]
**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**

**Describe the bug**

_A clear and concise description of what the bug is._
_Always attach (upload, do not copy/paste) the log file that can be found at `%LocalAppData%\pimax-openxr\logs` or opened from the PimaxXR Control Center app._

**Environment**

- _Application/Game and version_: 
- _Version of Pitool or Pimax client_: 

**To Reproduce**

_Steps to reproduce the behavior:_

1. Run '....' game
2. Enable option '....'
3. See error

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Comment by Fanta476** [comment]
At Half Life Alyx, the Controller Bindings are Buged.

If i use PimaxXR, i cant move forward with my Left Controller Stick, only if i click it down!
And on the Left anf Right Controller, it turns automatically if i Push on the Left Controller the "X"and on the Right Controller the "A" Button!
Works all fine if i am using SteamVR.

I am using a Pimax Crystal on HLA, with PimaxXR - v0.4.0/ OpenXR Toolkit - GA-3 (v1.3.2) and OpenXR.

**Comment by mbucchia** [comment]
As far as I know, the controller binding bugs are issues with OpenComposite, not something I can fix in PimaxXR.

**Comment by Fanta476** [comment]
Thanks for the reply and for letting me know.

**Comment by mbucchia** [comment]
I have tested with HP Reverb G2 and I observe the same issues you've described. Definitely an OpenComposite bug and not anything that I can fix myself in PimaxXR.
