### ISSUE TITLE
Intermittent flashing or flickering while in MSFS 2020

### ISSUE THREAD

**Issue by Hwnpilot** [mbucchia/Pimax-OpenXR#64]
Hi,
I am using a Gigabyte RTX 4090 with an AMD 5900X CPU. I have had no issues using Open XR Toolkit with my Reverb g2.
Just received the Pimax Crystal headset.  When running MSFS 2020, and using the default  SteamXR the program runs without problems. If I switch to PimaxXR Runtime and select PimaxXR, the program opens correctly but immediately it begins to flicker heavily while in PimaxXR.  If I swith back to SteamXR, the problems goes away.
Is there anyway I can fix this?
Thank You

**Comment by mbucchia** [comment]
Log file please
Are you using OpenXR Toolkit?
Are you using Smart Smoothing?
Have you tried unchecked "Prefer framerate over latency".

**Comment by Hwnpilot** [comment]
Thanks Matt, for getting back to me.  I will try and get a log file to you.  Im afraid I am not all that computer literate but really enjoy MSFS and how your programs have really enhanced it.
With the new Crystal I got 2 days ago,I use both Open XR toolkit and the and your PimaXR Runtime.
I am using Smart Smoothing and have not checked framerate over latency.
Since emailing you MSFS has decided to go and not finish loading.  All is normal until 99% loading and there it sits.  My 4090 is showing 97% utilization and will not go further, no mater how long I wait.  Have rebooted several times with and without Crystal connected but to no avail. May have to delete and re-install which will be a huge task. Not sure what to do now.

**Comment by Hwnpilot** [comment]
Thanks Ill look into that.  I will try and attach some log files: Not sure I did it correctly

Peter

**Comment by mbucchia** [comment]
I can't really do anything about smart smoothing issues. Closing.
