### ISSUE TITLE
No support for parent path bindings

### ISSUE THREAD

**Issue by Wyverex42** [mbucchia/Pimax-OpenXR#65]
**Describe the bug**

This is a conformity issue with the OpenXR standard. I know that this runtime isn't officially conformant but it seems like a worthwhile thing to conform to.

In https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#input-suggested-bindings the standard requires a runtime to accept a parent binding path like `/user/input/left/aim` (instead of `/user/input/left/aim/pose`) or `/user/input/left/a` (instead of `/user/input/left/a/click`) and to add the missing input component to its best ability.

E.g.
> If the path refers to the parent of input values instead of to an input value itself, the runtime **must** use …/example/path/pose instead of …/example/path if it is available. In any other situation the runtime **may** provide an alternate binding for the action or it will be unbound.

I assume that the standard is written that way so that apps can work across a larger subset of runtimes. If a runtime doesn't support one particular input component, it can still substitute it with another one. In that situation suggesting the parent path would work on more runtimes while insisting on a particular input component could break with others.

My app was trying to bind `/user/input/left/aim` for the Pimax Crystal controller but currently bindings that are suggested as a parent path are rejected with XR_ERROR_PATH_UNSUPPORTED.
 

**Environment**

- _Application/Game and version_: IvyVR
- _Version of Pitool or Pimax client_: 1.13.02.01

**To Reproduce**

_Steps to reproduce the behavior:_

1. Have any OpenXR app suggest an interaction profile path without an input component
2. Observe that XR_ERROR_PATH_UNSUPPORTED is returned

**Expected behavior**

Parent paths should be extended by the appropriate input component.

**Comment by mbucchia** [comment]
Thanks for the report. I think it's only  handful of them that are missing, in particular the aim/grip ones, and the A Button. All the other ones should break here, but I will conduct a review.

**Comment by mbucchia** [comment]
Fixed by a5a43f93802f3865872072c4d74ecbf534d746d3.
