### ISSUE TITLE
OpenXR Toolkit does not show menu F1 on Pimax Crystal in Windows 11

### ISSUE THREAD

**Issue by mibo46** [mbucchia/Pimax-OpenXR#68]
Have Pimax Client running, OpenXR Toolkit companion app open and PimaxVR control center as well as OpenComposite
When in VR trying the Crystal it does not show the menu so I can't put my settings for 3080 as shown from Pimax and Disco-VR Tetiana in Youtube. What should I do. Have tried everything for the last 4 hours

**Comment by mbucchia** [comment]
Your game probably isn't using OpenXR. Also "F1" was never the key to bring up the menu.

Start attaching some log files if you want help, because as it is, your query is way too vague.

There's a troubleshooting guide here: https://mbucchia.github.io/OpenXR-Toolkit/troubleshooting.html

**Comment by mibo46** [comment]
Thanks for your promt reply. I could now open the toolkit with F2 as said but with CTRL+F2
Have MSFS2020 and a Nvidia GeForce RTX 3080 video card, CPU is i7-13700K not overclocked.
Have tried all the settings of Tetiana from DiscoVR :"Best VR Performance of MSFS with RTX 3080. Opened Pimax Client, PimaxXR Control and Open Composite. 
Result: I cannot read well instruments and outside view is not optimal. My Reverb G2 is much better except Brighntness of Pimax Crystal that is better. Note that Tetiana from DiscoVR changed overriding resolution from  the OpenXR  System Tab from 3531x5106 to 2685x3883 and that gave her maximum sharpness and performance. On my headset (also Crystal) I cannot set this resolution. If I go to 2685 it shows 2685x3177. Have tried various settings up or down but it is never sharp. The sharpest one was 2685x3177 but a lot less sharp than Reverb G2. Also the settings of Tetiana in Performance Tab under Size 47% do not result the same in mine.
Can you help me?
Attached my log file






On Saturday, August 19, 2023 at 12:22:51 AM AST, Matthieu Bucchianeri ***@***.***> wrote: 







Your game probably isn't using OpenXR. Also "F1" was never the key to bring up the menu.

Start attaching some log files if you want help, because as it is, your query is way too vague.

There's a troubleshooting guide here: https://mbucchia.github.io/OpenXR-Toolkit/troubleshooting.html

**Comment by mbucchia** [comment]
Sorry, I'm only providing assistance with technical issues, not settings.

Settings are something for you to figure out and taylor specifically to your system. Can't help with that.

**Comment by mbucchia** [comment]
The MSFS forum has many threads about VR settings, you will get much better input there:

https://forums.flightsimulator.com/c/gd-commsupport/vr/227
