### ISSUE TITLE
Blinking with OpenKneeboard

### ISSUE THREAD

**Issue by ags313** [mbucchia/Pimax-OpenXR#7]
Hi, I get blinking (visible/invisible) when I open OpenKneeboard (https://github.com/fredemmott/OpenKneeboard), until it gets moved a few times, then it settles. 
I do not know if that issue should go here or to OpenKneeboard.

**Comment by mbucchia** [comment]
Can you clarify "until it gets moved a few times, then it settles."? Any chance you could capture a video of the problem?

**Comment by ags313** [comment]
By moved I mean press recenter button while looking elsewhere, which positions kneeboard far, this way I can put the blinking out of sight. No chance for video during the next week.

**Comment by mbucchia** [comment]
I was actually able to reproduce the blinking with a test application that submits a quad layer (this is what OpenKneeboard does). However with another application (OpenXR Toolkit) no issue. I will look into the possible cause.

**Comment by ags313** [comment]
Fingers crossed, and thank you!

**Comment by mbucchia** [comment]
I believe I have a fix for this now.

**Comment by mbucchia** [comment]
This should be fixed by e300ef9c22f2903568bba2ff5231adfa76632c7d and available in the next release.

**Comment by mbucchia** [comment]
[PimaxXR-0.2.1b.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9035861/PimaxXR-0.2.1b.zip)

Can you test with this experimental build and confirm the fix? Thanks.

**Comment by ags313** [comment]
On it.

**Comment by mbucchia** [comment]
Can you try without motion smoothing? Just to see if the knee board issue is solved?

Alternatively, you can add the following registry key:
`HKEY_LOCAL_MACHINE\SOFTWARE\PimaxXR`
`do_frame_begin`, dword value 1

**Comment by mbucchia** [comment]
I have no idea what is up with the Pimax software variations from a machine to another. Somebody else is reporting the same issue as you. But for me it's working 100% well in DCS...

**Comment by ags313** [comment]
Added the registry fix, trying this version again.

**Comment by ags313** [comment]
No blinking in OpenKneeboard.

**Comment by mbucchia** [comment]
Awesome! Working on fixing some issues with motion smoothing, which caused the issue without the reg fix.

Thanks for validating OpenKneeboard!
